import type { Preset } from '@/types/preset';

export const BUILTIN_PRESETS: Preset[] = [
  {
    id: 'web-h264',
    name: 'Web (H.264/AAC)',
    description: 'Web配信向け H.264 + AAC、CRF 23',
    category: 'web',
    isBuiltin: true,
    command: {
      inputPath: '',
      outputPath: '',
      videoCodec: 'libx264',
      audioCodec: 'aac',
      crf: 23,
      preset: 'fast',
      audioBitrate: '192k',
      container: 'mp4',
      filters: [],
      extraArgs: [],
      twoPass: false,
      copyVideo: false,
      copyAudio: false,
      noVideo: false,
      noAudio: false,
    },
  },
  {
    id: 'web-h265',
    name: 'Web (H.265/AAC)',
    description: '高圧縮 H.265 + AAC、CRF 28',
    category: 'web',
    isBuiltin: true,
    command: {
      inputPath: '',
      outputPath: '',
      videoCodec: 'libx265',
      audioCodec: 'aac',
      crf: 28,
      preset: 'fast',
      audioBitrate: '192k',
      container: 'mp4',
      filters: [],
      extraArgs: [],
      twoPass: false,
      copyVideo: false,
      copyAudio: false,
      noVideo: false,
      noAudio: false,
    },
  },
  {
    id: 'web-vp9',
    name: 'WebM (VP9/Opus)',
    description: 'ブラウザ対応 VP9 + Opus',
    category: 'web',
    isBuiltin: true,
    command: {
      inputPath: '',
      outputPath: '',
      videoCodec: 'libvpx-vp9',
      audioCodec: 'libopus',
      crf: 33,
      audioBitrate: '128k',
      container: 'webm',
      filters: [],
      extraArgs: [],
      twoPass: false,
      copyVideo: false,
      copyAudio: false,
      noVideo: false,
      noAudio: false,
    },
  },
  {
    id: 'social-instagram',
    name: 'Instagram (1080×1080)',
    description: 'Instagram正方形動画 1:1',
    category: 'social',
    isBuiltin: true,
    command: {
      inputPath: '',
      outputPath: '',
      videoCodec: 'libx264',
      audioCodec: 'aac',
      crf: 23,
      preset: 'fast',
      resolution: { width: 1080, height: 1080 },
      audioBitrate: '192k',
      container: 'mp4',
      filters: [],
      extraArgs: [],
      twoPass: false,
      copyVideo: false,
      copyAudio: false,
      noVideo: false,
      noAudio: false,
    },
  },
  {
    id: 'social-twitter',
    name: 'Twitter/X (1280×720)',
    description: 'Twitter/X 動画 720p',
    category: 'social',
    isBuiltin: true,
    command: {
      inputPath: '',
      outputPath: '',
      videoCodec: 'libx264',
      audioCodec: 'aac',
      crf: 23,
      preset: 'fast',
      resolution: { width: 1280, height: 720 },
      fps: 30,
      audioBitrate: '128k',
      container: 'mp4',
      filters: [],
      extraArgs: [],
      twoPass: false,
      copyVideo: false,
      copyAudio: false,
      noVideo: false,
      noAudio: false,
    },
  },
  {
    id: 'archive-copy',
    name: 'アーカイブ (再エンコードなし)',
    description: 'コンテナ変換のみ',
    category: 'archive',
    isBuiltin: true,
    command: {
      inputPath: '',
      outputPath: '',
      copyVideo: true,
      copyAudio: true,
      container: 'mkv',
      filters: [],
      extraArgs: [],
      twoPass: false,
      noVideo: false,
      noAudio: false,
    },
  },
  {
    id: 'audio-mp3',
    name: '音声抽出 (MP3)',
    description: '映像なし、MP3 高品質',
    category: 'audio',
    isBuiltin: true,
    command: {
      inputPath: '',
      outputPath: '',
      audioCodec: 'libmp3lame',
      noVideo: true,
      extraArgs: ['-q:a', '2'],
      filters: [],
      twoPass: false,
      copyVideo: false,
      copyAudio: false,
      noAudio: false,
    },
  },
  {
    id: 'audio-flac',
    name: '音声抽出 (FLAC)',
    description: '映像なし、FLACロスレス',
    category: 'audio',
    isBuiltin: true,
    command: {
      inputPath: '',
      outputPath: '',
      audioCodec: 'flac',
      noVideo: true,
      filters: [],
      extraArgs: [],
      twoPass: false,
      copyVideo: false,
      copyAudio: false,
      noAudio: false,
    },
  },
];

export const PRESET_CATEGORIES = [
  { id: 'web' as const, labelKey: 'presets.web' },
  { id: 'social' as const, labelKey: 'presets.social' },
  { id: 'archive' as const, labelKey: 'presets.archive' },
  { id: 'audio' as const, labelKey: 'presets.audio' },
  { id: 'custom' as const, labelKey: 'presets.custom' },
];

/** 映像コーデック選択肢 */
export const VIDEO_CODECS = [
  {
    id: 'libx264',
    name: 'H.264',
    hwVariants: ['h264_nvenc', 'h264_qsv', 'h264_videotoolbox'],
  },
  {
    id: 'libx265',
    name: 'H.265/HEVC',
    hwVariants: ['hevc_nvenc', 'hevc_qsv', 'hevc_videotoolbox'],
  },
  { id: 'libvpx-vp9', name: 'VP9', hwVariants: [] },
  { id: 'libaom-av1', name: 'AV1', hwVariants: ['av1_nvenc', 'av1_qsv'] },
  { id: 'prores_ks', name: 'ProRes', hwVariants: [] },
  { id: 'copy', name: 'コピー (再エンコードなし)', hwVariants: [] },
] as const;

/** 音声コーデック選択肢 */
export const AUDIO_CODECS = [
  { id: 'aac', name: 'AAC' },
  { id: 'libmp3lame', name: 'MP3' },
  { id: 'libopus', name: 'Opus' },
  { id: 'flac', name: 'FLAC' },
  { id: 'pcm_s16le', name: 'PCM (WAV)' },
  { id: 'copy', name: 'コピー' },
] as const;

/** コンテナフォーマット */
export const CONTAINERS = [
  { id: 'mp4', name: 'MP4', extension: 'mp4' },
  { id: 'webm', name: 'WebM', extension: 'webm' },
  { id: 'mkv', name: 'MKV', extension: 'mkv' },
  { id: 'mov', name: 'MOV', extension: 'mov' },
  { id: 'avi', name: 'AVI', extension: 'avi' },
  { id: 'flv', name: 'FLV', extension: 'flv' },
  { id: 'ts', name: 'TS', extension: 'ts' },
  { id: 'gif', name: 'GIF', extension: 'gif' },
  { id: 'mp3', name: 'MP3 (音声)', extension: 'mp3' },
  { id: 'flac', name: 'FLAC (音声)', extension: 'flac' },
  { id: 'wav', name: 'WAV (音声)', extension: 'wav' },
] as const;

/** 解像度プリセット */
export const RESOLUTION_PRESETS = [
  { id: 'original', name: '元のサイズを維持', width: null, height: null },
  { id: '4k', name: '4K (3840×2160)', width: 3840, height: 2160 },
  { id: '1440p', name: '1440p (2560×1440)', width: 2560, height: 1440 },
  { id: '1080p', name: '1080p (1920×1080)', width: 1920, height: 1080 },
  { id: '720p', name: '720p (1280×720)', width: 1280, height: 720 },
  { id: '480p', name: '480p (854×480)', width: 854, height: 480 },
  { id: '360p', name: '360p (640×360)', width: 640, height: 360 },
  { id: 'custom', name: 'カスタム', width: null, height: null },
] as const;

/** フレームレート選択肢 */
export const FPS_OPTIONS = [
  { value: null, label: '元のFPSを維持' },
  { value: 23.976, label: '23.976 fps' },
  { value: 24, label: '24 fps' },
  { value: 25, label: '25 fps' },
  { value: 29.97, label: '29.97 fps' },
  { value: 30, label: '30 fps' },
  { value: 48, label: '48 fps' },
  { value: 50, label: '50 fps' },
  { value: 59.94, label: '59.94 fps' },
  { value: 60, label: '60 fps' },
] as const;
